const fs=require('fs'),vm=require('vm'),assert=require('assert');const {parseHTML}=require('linkedom');
let source=fs.readFileSync(require('path').join(__dirname,'Dane-Torn-Console.user.js'),'utf8');assert(!/[^\x00-\x7f]/.test(source));source=source.replace('hydrateEquipment();observe();render();if(route().items)captureDOM();queueInline();','globalThis.test={readLog,parseEvent,analyze,ffInfo,proc,refreshInline,navigation,cleanItemName,classifyInventory,forecastView,profile,endpointCaps,hydrateEquipment,marketEval,meritPlan,battleAdvice,fightContext,weaponOptions,debriefAdvice,mountCombatPanel,saveProfile,accountWrite};');
const {window}=parseHTML('<html><body><main id="mainContainer"><h1>Attack log<span></span></h1><div id="events"></div></main></body></html>');const {document}=window;Object.defineProperty(window.HTMLSelectElement.prototype,"value",{get(){return this.querySelector("option[selected]")?.textContent||this.querySelector("option")?.textContent||"";},set(v){for(const o of this.querySelectorAll("option")){if(o.textContent===v)o.setAttribute("selected","");else o.removeAttribute("selected");}},configurable:true});const store=new Map();const location={href:'https://www.torn.com/loader.php?sid=attackLog&ID=123'};const ctx={document,window,location,navigator:{},console,URL,DOMException,AbortController,crypto:require('crypto').webcrypto,MutationObserver:window.MutationObserver,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},GM_getValue:(k,d)=>store.has(k)?store.get(k):d,GM_setValue:(k,v)=>store.set(k,v),GM_deleteValue:k=>store.delete(k),GM_listValues:()=>[...store.keys()],GM_registerMenuCommand(){},GM_addValueChangeListener(){},GM_xmlhttpRequest(){throw Error('Unexpected network request');}};vm.createContext(ctx);vm.runInContext(source,ctx);const t=ctx.test;
const rows=[['Someone mugged Dane_Moore for $16,533','00:31:46'],['Someone critically hit Dane_Moore with their Diamond Bladed Knife for 2380','00:31:43'],["Dane_Moore sprayed Pepper Spray in Someone's face",'00:31:42'],['Someone hit Dane_Moore with their Diamond Bladed Knife for 1420','00:31:42'],['Someone initiated an attack against Dane_Moore','00:31:40']];document.querySelector('#events').innerHTML=rows.map(([text,time])=>`<div class="row"><div>${text}</div><div class="time">${time}</div></div>`).join('');let log=t.readLog();assert(log);assert.equal(log.events.length,5);assert.equal(log.p.a,'Someone');assert.equal(log.a.damage,3800);assert.equal(log.b.damage,0);assert.equal(log.a.crits,1);assert.equal(log.events[0].type,'start');assert.equal(log.events.at(-1).type,'outcome');assert.equal(log.events[2].type,'temp');assert(!JSON.stringify(log).includes('heading'));t.profile.name='Dane_Moore';t.refreshInline();assert.equal(document.querySelectorAll('[data-dtc-inline]').length,1);assert(document.querySelector('[data-dtc-inline]').shadowRoot.innerHTML.includes('Combat debrief'));t.refreshInline();assert.equal(document.querySelectorAll('[data-dtc-inline]').length,1);
assert.equal(t.cleanItemName('x5 Adhesive Plastic x5 $495 | 5x = $2,475'),'Adhesive Plastic');assert.equal(t.cleanItemName('Aluminum Plate x73'),'Aluminum Plate');assert(t.endpointCaps.Inventory.includes('cat=Medical'));
location.href='https://www.torn.com/loader.php?sid=attack&user2ID=123';document.querySelector('#mainContainer').innerHTML='<h1>Attacking</h1><div>FairFight: 1.05? (Easy) (4 months old) Est. Stats: 2.45k</div><div>Battle Stats: 7.235mil</div>';assert.equal(t.ffInfo().estimate,2450);assert.equal(t.ffInfo().displayedOwn,7235000);assert.equal(t.ffInfo().age,'4 months old');t.refreshInline();assert.equal(document.querySelectorAll('[data-dtc-inline]').length,1);assert(document.querySelector('[data-dtc-inline]').shadowRoot.innerHTML.includes('Combat advisor'));assert(t.forecastView().includes('Sync combat data'));assert(!t.forecastView().includes('Suggested opener: primary'));location.href='https://www.torn.com/item.php';t.refreshInline();assert.equal(document.querySelectorAll('[data-dtc-inline]').length,0);
assert(Math.abs(t.proc(17,3)-42.8213)<.001);const p={a:'Dane_Moore',b:'Big-Tuna'};const ev=[];for(let i=0;i<10;i++)ev.push(t.parseEvent(i<7?`Dane_Moore hit Big-Tuna with their Dagger for ${[1521,500,400,300,300,300,261][i]} 00:00:01`:'Dane_Moore fired their Dagger missing Big-Tuna 00:00:01',p));for(let i=0;i<10;i++)ev.push(t.parseEvent(i<9?`Big-Tuna hit Dane_Moore with their Knife for ${[1430,300,300,300,300,300,200,200,86][i]} 00:00:02`:'Big-Tuna fired their Knife missing Dane_Moore 00:00:02',p));for(const x of ['Big-Tuna is withered','Big-Tuna is withered','Big-Tuna is stunned'])ev.push(t.parseEvent(x+' 00:00:03',p));for(let i=0;i<4;i++)ev.push(t.parseEvent('Dane_Moore reloaded 00:00:04',p));const a=t.analyze(ev,p.a),b=t.analyze(ev,p.b);assert.equal(ev.length,27);assert.equal(a.damage,3582);assert.equal(b.damage,3416);assert.equal(a.accuracy,70);assert.equal(b.accuracy,90);assert.equal(a.procs.Wither,2);assert.equal(a.procs.Stun,1);assert.equal(a.max,1521);assert.equal(b.max,1430);
console.log('PASS: syntax/ASCII; screenshot 5-event log; nested timestamp cells; outcome cash excluded; 27-event regression; inline mount/dedup/SPA removal; FF age/stats; missing-loadout guidance; inventory names/category; proc math.');
// Additional v8.2 behavior tests, independent of any API key.
t.profile.strategy='Tank Ninja';t.profile.gear.primary={...t.profile.gear.primary,name:'Mag 7',class:'Shotgun',damage:64.92,accuracy:68.23,bonuses:{stun:17}};t.profile.gear.melee={...t.profile.gear.melee,name:'Dagger',class:'Piercing',damage:38.71,accuracy:67.43,bonuses:{wither:36,puncture:15}};t.profile.gear.secondary={...t.profile.gear.secondary,name:'BT MP9',class:'SMG',damage:67.04,accuracy:60.33,bonuses:{slow:20}};
let context={i:{age:'4 months old',min:1000000,max:10000000},own:7235393,estimate:3000000,ratio:2.4,cautiousRatio:.72,blocked:false,merits:{rows:[{name:'Shotgun Mastery',level:8},{name:'SMG Mastery',level:1}],at:0}};
let advice=t.battleAdvice(context);assert.equal(advice.opener.g.name,'Dagger');assert(advice.plan.some(x=>x.includes('After Wither')));assert(advice.warnings.some(x=>x.includes('exceeds')));assert(advice.warnings.some(x=>x.includes('4 months')));assert(advice.reasons.some(x=>x.includes('Shotgun Mastery')));
context={...context,ratio:20,cautiousRatio:5};advice=t.battleAdvice(context);assert.equal(advice.opener.g.name,'Mag 7');assert(advice.plan.some(x=>x.includes('short fight')));context.blocked=true;assert(t.battleAdvice(context).warnings.some(x=>x.includes('enough energy')));
t.profile.stats={strength:3000000,defense:3000000,speed:100000,dexterity:1135393};assert(t.battleAdvice(context).warnings.some(x=>x.includes('speed is less than half')));
let reviewed={p,events:ev,a,b};const adviceHTML=t.debriefAdvice(reviewed,'Dane_Moore');assert(adviceHTML.includes('Accuracy was a weak point'));assert(adviceHTML.includes('large hit'));assert(adviceHTML.includes('Wither arrived late'));assert(adviceHTML.includes('Current build')===false);
// Simulate a floated fixed-height heading like Torn: panel must be its sibling.
location.href='https://www.torn.com/loader.php?sid=attack';document.querySelector('#mainContainer').innerHTML='<div class="content-wrapper"><div class="header" style="height:30px"><h1 style="float:left">Attacking</h1></div><div class="combatants">Fight controls</div></div>';
t.refreshInline();const panel=document.querySelector('[data-dtc-inline]');assert(panel);assert.equal(panel.parentElement.className,'content-wrapper');assert(!panel.closest('.header'));assert(panel.nextElementSibling.className==='header');assert(panel.style.cssText.includes('position:relative'));assert(panel.shadowRoot.innerHTML.includes('max-height:70vh'));
// Updated metadata uses only native update hooks, not fetched-code execution.
assert(source.includes('// @updateURL    https://raw.githubusercontent.com/Danieltv31/Dane/master/dane-torn-console/Dane-Torn-Console.user.js'));assert(!/\beval\s*\(|new Function\s*\(/.test(source));
console.log('PASS: equipment/mastery-sensitive opener; conservative estimate range; energy/stale-data warnings; stat imbalance; shortcomings/next steps; header collision fixture; native update metadata.');
